#!/usr/bin/env python3
"""格子(--grid)の学習結果から、打鍵時予測の表(Rustのデータ)を生成する(ADR-191 決定3・4)。

  gen_key_effect_table.py            grid-tables/{atok,msime}.json → crates/awase-windows/src/state/key_effect_data.rs

入力JSON: `"<状態>|<キー>" → {"ON/0x19/保持": 回数, ...}`(grid_learn.py --json の出力)。
状態名 = `on|off - c<conv> - <段階>`(段階: none / typing / conv-space / conv-henkan / conv-muhenkan)。
`typing-prev-*` は履歴依存の追加ブロックなので表には入れない。
採用するセル = 結果が**全試行で一致**したセルだけ(多数派<100%の非決定セルと未観測セルは「予測なし」)。
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "..", "crates", "awase-windows", "src", "state", "key_effect_data.rs")

KEYS = {
    "bs": "Bs", "eisu": "Eisu", "enter": "Enter", "esc": "Esc", "hankaku-zenkaku": "HankakuZenkaku",
    "henkan": "Henkan", "hiragana": "Hiragana", "ime-off": "ImeOff", "ime-on": "ImeOn", "kanji": "Kanji",
    "katakana": "Katakana", "muhenkan": "Muhenkan", "space": "Space",
}
STAGES = {"none": "None", "typing": "Typing", "conv-space": "ConvSpace", "conv-henkan": "ConvHenkan", "conv-muhenkan": "ConvMuhenkan"}
DISP = {None: "None", "保持": "Kept", "破棄": "Discarded", "確定": "Committed"}
STATE_RE = re.compile(r"^(on|off)-c([0-9A-F]{2})-(none|typing|conv-space|conv-henkan|conv-muhenkan)$")
RES_RE = re.compile(r"^(ON|OFF)/0x([0-9A-F]{2})(?:/(保持|破棄|確定))?$")


def cells(path):
    d = json.load(open(path, encoding="utf-8"))
    out, skipped = [], {"nondeterministic": 0, "history": 0, "other": 0}
    for cell, dist in sorted(d.items()):
        state, key = cell.split("|")
        m = STATE_RE.match(state)
        if not m:
            skipped["history" if "prev-" in state else "other"] += 1
            continue
        if key not in KEYS:
            skipped["other"] += 1
            continue
        if len(dist) != 1:
            skipped["nondeterministic"] += 1
            continue
        (res,) = dist
        r = RES_RE.match(res)
        if not r:
            skipped["other"] += 1
            continue
        out.append((m.group(1) == "on", m.group(2), STAGES[m.group(3)], KEYS[key],
                    r.group(1) == "ON", r.group(2), DISP[r.group(3)]))
    return out, skipped


def emit(name, cs):
    lines = ["#[rustfmt::skip]", f"pub(super) const {name}: &[Cell] = &["]
    for o, c, st, k, o2, c2, dp in cs:
        lines.append(f"    cell({str(o).lower()}, Conv::C{c}, Stage::{st}, TableKey::{k}, {str(o2).lower()}, Conv::C{c2}, Disp::{dp}),")
    lines.append("];")
    return "\n".join(lines)


def main():
    parts = ["""// @generated by tools/e2e/ime_key_matrix/gen_key_effect_table.py — 手で編集しない（ADR-191 決定3・4）。
// 生成元: tools/e2e/ime_key_matrix/grid-tables/{atok,msime}.json（GitHub CI の --grid 学習結果、各1,336試行）。
// 全試行で結果が一致したセルだけを含む（非決定セル・未観測セル・履歴依存の追加ブロックは「予測なし」）。
// MS-IME は「GJI の MS-IME プリセット」の表（Microsoft IME 本体ではない）。

use super::key_effect_table::{cell, Cell, Conv, Disp, Stage, TableKey};
"""]
    report = []
    for name, f in (("ATOK", "atok.json"), ("MSIME", "msime.json")):
        cs, sk = cells(os.path.join(HERE, "grid-tables", f))
        parts.append(emit(name, cs))
        report.append(f"{name}: {len(cs)}セル採用、除外 {sk}")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts) + "\n")
    print("\n".join(report))


if __name__ == "__main__":
    sys.exit(main())
