// @generated by tools/e2e/ime_key_matrix/gen_key_effect_table.py — 手で編集しない（ADR-191 決定3・4）。
// 生成元: tools/e2e/ime_key_matrix/grid-tables/{atok,msime,msime-native}.json（GitHub CI の --grid --grid-setup=keys 学習結果=第3版。全状態をキーだけで作る）。
// 全試行で結果が一致したセルだけを含む（非決定セル・未観測セル・履歴依存の追加ブロックは「予測なし」）。
// 閉(OFF)のセルは変換モードを問わない（conv=None）。押下後convが不明なセルは after_conv=None（追跡を捨てる）。
// MSIME は「GJI の MS-IME プリセット」の表（Microsoft IME 本体ではない）。MSIME_NATIVE が Microsoft IME 本体の表。
// MSIME は各セル2試行で非決定を検出しきれないため、ATOK で割れた変換中のEsc・入力中のBS/Escは変換モードを問わず除外した。
// MSIME_NATIVE は206/227セルが1試行のみ（独立walkの採点で確認、非決定6セルは除外済み）。
// 測定環境: 不明(grid-tables/measurement-env.json が無いか読めない、ADR-196決定1d参照)

use super::key_effect_predictor::{cell, Cell, Conv, Disp, Stage, TableKey};

#[rustfmt::skip]
pub(super) const ATOK: &[Cell] = &[
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Esc, true, Some(Conv::C10), Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Bs, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Enter, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Esc, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOn, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Katakana, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Space, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Esc, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];
#[rustfmt::skip]
pub(super) const MSIME: &[Cell] = &[
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Bs, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Enter, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Esc, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Henkan, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOn, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Muhenkan, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Space, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Henkan, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Bs, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Enter, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Esc, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Henkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOn, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Space, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];
#[rustfmt::skip]
pub(super) const MSIME_NATIVE: &[Cell] = &[
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Bs, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Enter, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Esc, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Space, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];

// --- ADR-192 classification logic (the generator preserves this suffix) ---

/// 状態依存性を判定できない理由（ADR-192決定1）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CannotPredictReason {
    /// キーマップの解釈自体が不確か。
    AmbiguousKeymap,
    /// ユーザー固有の上書きが対象キーの意味を変えている。
    UserOverride,
    /// awase側の実測データが不足している。
    InsufficientData,
}

/// 状態依存性が見つかった軸。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StateDependentAxis {
    /// IMEの開閉結果が入力前の状態だけでは決まらない。
    Open,
    /// 未確定文字列の破棄・確定が入力状態によって変わる。
    Composition,
    /// 開閉と未確定文字列の両方。
    OpenAndComposition,
}

/// 対象IMEモードキーの状態依存性（ADR-192決定1）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Classification {
    StateIndependent,
    StateDependent(StateDependentAxis),
    CannotPredict(CannotPredictReason),
}

/// 実測セルを直接横断してIMEモードキーの状態依存性を分類する。
///
/// 対象外のVKは`None`。`KeyEffectKeymap::predict`は実行時向け補正を含むため使わない。
#[must_use]
pub fn classify_state_dependent_mode_key(
    keymap: Option<&super::key_effect_predictor::KeyEffectKeymap>,
    vk: u16,
) -> Option<Classification> {
    use super::key_effect_predictor::{custom_table_overrides, KeymapPreset, TableKey};

    let key = match vk {
        0x1C => TableKey::Henkan,
        0x1D => TableKey::Muhenkan,
        0xF3 | 0xF4 => TableKey::HankakuZenkaku,
        0x19 => TableKey::Kanji,
        0x16 => TableKey::ImeOn,
        0x1A => TableKey::ImeOff,
        _ => return None,
    };
    let Some(keymap) = keymap else {
        return Some(Classification::CannotPredict(
            CannotPredictReason::AmbiguousKeymap,
        ));
    };
    if matches!(
        keymap.preset,
        KeymapPreset::MsImeNative | KeymapPreset::Custom
    ) {
        // MsImeNativeと同じ理由: 基準となる同梱表が無い(Customは`session_keymap`が
        // ATOK/MSIME以外、ADR-195段階4 B3対応で`from_config`が`None`ではなく
        // `Custom`プリセットを返すようになった)。
        return Some(Classification::CannotPredict(
            CannotPredictReason::InsufficientData,
        ));
    }
    if keymap.has_overlay && matches!(key, TableKey::Henkan | TableKey::Muhenkan) {
        return Some(Classification::CannotPredict(
            CannotPredictReason::AmbiguousKeymap,
        ));
    }
    if let Some(custom) = keymap.custom_table.as_deref() {
        // ATOKプリセットでは古いcustom_keymap_tableを信頼できない（ADR-186決定(c)）。
        if keymap.preset == KeymapPreset::Atok {
            return Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap,
            ));
        }
        if custom_table_overrides(custom, vk) {
            return Some(Classification::CannotPredict(
                CannotPredictReason::UserOverride,
            ));
        }
    }

    let cells = match keymap.preset {
        KeymapPreset::Atok => ATOK,
        KeymapPreset::MsIme => MSIME,
        KeymapPreset::MsImeNative | KeymapPreset::Custom => unreachable!("handled above"),
    };
    Some(classify_cells(cells, key, vk))
}

fn classify_cells(cells: &[Cell], key: TableKey, vk: u16) -> Classification {
    let matching: Vec<_> = cells.iter().filter(|cell| cell.key == key).collect();
    if matching.is_empty() {
        return Classification::CannotPredict(CannotPredictReason::InsufficientData);
    }

    let set_on = matching.iter().all(|cell| cell.after_open);
    let set_off = matching.iter().all(|cell| !cell.after_open);
    let toggle = matching.iter().all(|cell| cell.after_open != cell.open);
    let identity = matching.iter().all(|cell| cell.after_open == cell.open);
    let open_dependent = !(set_on || set_off || toggle || identity);

    let composition_dependent = !identity
        && crate::vk::is_physical_ime_mode_key(awase::types::VkCode(vk))
        && [Disp::Discarded, Disp::Committed]
            .into_iter()
            .any(|hazard| {
                let hazardous = matching.iter().filter(|cell| cell.disp == hazard).count();
                hazardous > 0 && hazardous < matching.len()
            });

    match (open_dependent, composition_dependent) {
        (false, false) => Classification::StateIndependent,
        (true, false) => Classification::StateDependent(StateDependentAxis::Open),
        (false, true) => Classification::StateDependent(StateDependentAxis::Composition),
        (true, true) => Classification::StateDependent(StateDependentAxis::OpenAndComposition),
    }
}

#[cfg(test)]
mod classification_tests {
    use super::*;
    use crate::state::key_effect_predictor::KeyEffectKeymap;

    fn classify(preset: i64, vk: u16) -> Option<Classification> {
        let keymap = KeyEffectKeymap::from_config(Some(preset), None, &[]).unwrap();
        classify_state_dependent_mode_key(Some(&keymap), vk)
    }

    #[test]
    fn adr192_open_axis_verification_table() {
        for vk in [0x16, 0x1A, 0x19, 0xF3, 0xF4] {
            assert_ne!(
                classify(1, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
            assert_ne!(
                classify(2, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
        }
        for vk in [0x1C, 0x1D] {
            assert_eq!(
                classify(1, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
            assert_eq!(classify(2, vk), Some(Classification::StateIndependent));
        }
    }

    #[test]
    fn adr192_composition_axis_verification_table() {
        for preset in [1, 2] {
            for vk in [0x19, 0xF3, 0xF4] {
                assert_eq!(
                    classify(preset, vk),
                    Some(Classification::StateDependent(
                        StateDependentAxis::Composition
                    ))
                );
            }
            for vk in [0x16, 0x1A] {
                assert_eq!(classify(preset, vk), Some(Classification::StateIndependent));
            }
        }
    }

    #[test]
    fn adr192_non_target_keys_are_not_classified() {
        for vk in [0x08, 0x0D, 0x1B, 0x20, 0xF0, 0xF1, 0xF2] {
            assert_eq!(classify(1, vk), None);
        }
    }

    #[test]
    fn adr192_cannot_predict_reasons_are_distinct() {
        assert_eq!(
            classify_state_dependent_mode_key(None, 0x1C),
            Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap
            ))
        );
        let overlay = KeyEffectKeymap::from_config(Some(2), None, &[1]).unwrap();
        assert_eq!(
            classify_state_dependent_mode_key(Some(&overlay), 0x1C),
            Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap
            ))
        );
        let custom = KeyEffectKeymap::from_config(
            Some(2),
            Some("DirectInput\tHenkan\tIMEOn".to_owned()),
            &[],
        )
        .unwrap();
        assert_eq!(
            classify_state_dependent_mode_key(Some(&custom), 0x1C),
            Some(Classification::CannotPredict(
                CannotPredictReason::UserOverride
            ))
        );
        let native = KeyEffectKeymap::for_msime_native(false, None, None);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&native), 0x1C),
            Some(Classification::CannotPredict(
                CannotPredictReason::InsufficientData
            ))
        );
    }
}
