// @generated by tools/e2e/ime_key_matrix/gen_key_effect_table.py — 手で編集しない（ADR-191 決定3・4）。
// 生成元: tools/e2e/ime_key_matrix/grid-tables/{atok,msime,msime-native}.json（GitHub CI の --grid --grid-setup=keys 学習結果=第3版。全状態をキーだけで作る）。
// 全試行で結果が一致したセルだけを含む（非決定セル・未観測セル・履歴依存の追加ブロックは「予測なし」）。
// 閉(OFF)のセルは変換モードを問わない（conv=None）。押下後convが不明なセルは after_conv=None（追跡を捨てる）。
// MSIME は「GJI の MS-IME プリセット」の表（Microsoft IME 本体ではない）。MSIME_NATIVE が Microsoft IME 本体の表。
// MSIME は各セル2試行で非決定を検出しきれないため、ATOK で割れた変換中のEsc・入力中のBS/Escは変換モードを問わず除外した。
// MSIME_NATIVE は206/227セルが1試行のみ（独立walkの採点で確認、非決定6セルは除外済み）。
// 測定環境: 不明(grid-tables/measurement-env.json が無いか読めない、ADR-196決定1d参照)

use super::key_effect_predictor::{cell, Cell, Conv, Disp, Stage, TableKey};

#[rustfmt::skip]
pub(super) const ATOK: &[Cell] = &[
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Esc, true, Some(Conv::C10), Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Bs, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Enter, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Esc, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOn, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Katakana, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Space, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Esc, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];
#[rustfmt::skip]
pub(super) const MSIME: &[Cell] = &[
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Bs, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Enter, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Esc, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Henkan, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOn, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Muhenkan, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Space, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Henkan, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Bs, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Enter, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Esc, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Henkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOn, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Space, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];
#[rustfmt::skip]
pub(super) const MSIME_NATIVE: &[Cell] = &[
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Bs, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Enter, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Esc, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Space, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];

// --- ADR-192 classification logic (the generator preserves this suffix) ---

/// 状態依存性を判定できない理由（ADR-192決定1）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CannotPredictReason {
    /// キーマップの解釈自体が不確か。
    AmbiguousKeymap,
    /// ユーザー固有の上書きが対象キーの意味を変えている。
    UserOverride,
    /// awase側の実測データが不足している。
    InsufficientData,
}

/// 状態依存性が見つかった軸。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StateDependentAxis {
    /// IMEの開閉結果が入力前の状態だけでは決まらない。
    Open,
    /// 未確定文字列の破棄・確定が入力状態によって変わる。
    Composition,
    /// 開閉と未確定文字列の両方。
    OpenAndComposition,
}

/// 対象IMEモードキーの状態依存性（ADR-192決定1）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Classification {
    StateIndependent,
    StateDependent(StateDependentAxis),
    CannotPredict(CannotPredictReason),
}

/// 実測セルを直接横断してIMEモードキーの状態依存性を分類する。
///
/// 対象外のVKは`None`。`KeyEffectKeymap::predict`は実行時向け補正を含むため使わない。
///
/// `learned`は実行時に採用されている学習表のセル（`RuntimeTableCache`、ADR-196/ADR192-T5）。
/// 対象キーのセルを持つときは、同梱表・キーマップ由来のガード（overlay/カスタム表）より先に
/// それで判定する（予測器`predict_with_override`と同じ優先順位。予測器が「冪等」と見ているキーを
/// この警告が「状態依存」と表示する食い違いを防ぐ）。対象キーのセルが無ければ従来どおり。
#[must_use]
pub fn classify_state_dependent_mode_key(
    keymap: Option<&super::key_effect_predictor::KeyEffectKeymap>,
    vk: u16,
    learned: Option<&[Cell]>,
) -> Option<Classification> {
    use super::key_effect_predictor::{custom_table_overrides, KeymapPreset, TableKey};

    let key = match vk {
        0x1C => TableKey::Henkan,
        0x1D => TableKey::Muhenkan,
        0xF3 | 0xF4 => TableKey::HankakuZenkaku,
        0x19 => TableKey::Kanji,
        0x16 => TableKey::ImeOn,
        0x1A => TableKey::ImeOff,
        _ => return None,
    };
    let Some(keymap) = keymap else {
        return Some(Classification::CannotPredict(
            CannotPredictReason::AmbiguousKeymap,
        ));
    };
    if let Some(learned) = learned {
        if learned.iter().any(|cell| cell.key == key) {
            return Some(classify_cells(learned, key, vk));
        }
    }
    if matches!(
        keymap.preset,
        KeymapPreset::MsImeNative | KeymapPreset::Custom
    ) {
        // MsImeNativeと同じ理由: 基準となる同梱表が無い(Customは`session_keymap`が
        // ATOK/MSIME以外、ADR-195段階4 B3対応で`from_config`が`None`ではなく
        // `Custom`プリセットを返すようになった)。
        return Some(Classification::CannotPredict(
            CannotPredictReason::InsufficientData,
        ));
    }
    if keymap.has_overlay && matches!(key, TableKey::Henkan | TableKey::Muhenkan) {
        return Some(Classification::CannotPredict(
            CannotPredictReason::AmbiguousKeymap,
        ));
    }
    if let Some(custom) = keymap.custom_table.as_deref() {
        // ATOKプリセットでは古いcustom_keymap_tableを信頼できない（ADR-186決定(c)）。
        if keymap.preset == KeymapPreset::Atok {
            return Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap,
            ));
        }
        if custom_table_overrides(custom, vk) {
            return Some(Classification::CannotPredict(
                CannotPredictReason::UserOverride,
            ));
        }
    }

    let cells = match keymap.preset {
        KeymapPreset::Atok => ATOK,
        KeymapPreset::MsIme => MSIME,
        KeymapPreset::MsImeNative | KeymapPreset::Custom => unreachable!("handled above"),
    };
    Some(classify_cells(cells, key, vk))
}

fn classify_cells(cells: &[Cell], key: TableKey, vk: u16) -> Classification {
    let matching: Vec<_> = cells.iter().filter(|cell| cell.key == key).collect();
    if matching.is_empty() {
        return Classification::CannotPredict(CannotPredictReason::InsufficientData);
    }

    let set_on = matching.iter().all(|cell| cell.after_open);
    let set_off = matching.iter().all(|cell| !cell.after_open);
    let toggle = matching.iter().all(|cell| cell.after_open != cell.open);
    let identity = matching.iter().all(|cell| cell.after_open == cell.open);
    let open_dependent = !(set_on || set_off || toggle || identity);

    let composition_dependent = !identity
        && crate::vk::is_physical_ime_mode_key(awase::types::VkCode(vk))
        && [Disp::Discarded, Disp::Committed]
            .into_iter()
            .any(|hazard| {
                let hazardous = matching.iter().filter(|cell| cell.disp == hazard).count();
                hazardous > 0 && hazardous < matching.len()
            });

    match (open_dependent, composition_dependent) {
        (false, false) => Classification::StateIndependent,
        (true, false) => Classification::StateDependent(StateDependentAxis::Open),
        (false, true) => Classification::StateDependent(StateDependentAxis::Composition),
        (true, true) => Classification::StateDependent(StateDependentAxis::OpenAndComposition),
    }
}

/// ADR-195 追記（縮小方向）: 採用中の学習表が、このキーを**開閉トグルでない**と示しているか。
///
/// 半角/全角（0xF3/0xF4）の固定セット`shadow_action=Toggle`を外してよいかの判定に使う純関数。
/// 誤って外すと belief 追随が予測に依存するようになるので、外すのは「予測が引けて、かつ
/// 非トグルが確からしい」ときだけにする（Opus round1 B1〜B3）:
/// - **`Stage::None`（入力中でない）のセルだけ**を見る。入力中のセルは MS-IME 本体のように
///   純トグルでない正規の挙動がある（開→開・半角英数へ切替）ので、開閉の割り当ての証拠にならない。
/// - 予測が引けることを前提にする: 閉セルと、開セルのうち`C19`（ひらがな）・`C10`（英数）の
///   両方が揃っているときだけ`true`になりうる（欠けていれば`false`＝外さない）。
/// - 非トグルの証拠: 開セルが**すべて**開→開（IMEOn・ひらがな系の割り当て）の方向だけ。開セル1つの
///   ノイズでは反転しない。閉セルは前提条件（存在するか）にだけ使い、閉→閉（IMEOff系の割り当て）の
///   検出は**見送っている**: 学習が閉セル1つを取りこぼしただけで判定が反転し、TsfNative で belief が
///   追随せず Engine OFF・IME ON のまま固定される退行を避けるため（Opus PR#308 M1）。
/// - 行が無い・セルが欠ける→`false`（固定セット維持）。
///
/// `classify_cells`（全セルを見て警告に使う）とは目的が違い、同じ基準ではない。
#[must_use]
pub fn learned_cells_show_non_toggle(cells: &[Cell], key: TableKey) -> bool {
    use super::key_effect_predictor::{Conv, Stage};
    let idle = || {
        cells
            .iter()
            .filter(move |c| c.key() == key && c.stage() == Stage::None)
    };
    let has_open = |conv: Conv| idle().any(|c| c.open() && c.conv() == Some(conv));
    if !idle().any(|c| !c.open()) || !has_open(Conv::C19) || !has_open(Conv::C10) {
        return false;
    }
    idle().filter(|c| c.open()).all(Cell::after_open)
}

#[cfg(test)]
mod classification_tests {
    use super::*;
    use crate::state::key_effect_predictor::KeyEffectKeymap;

    /// ADR-195追記: 半角/全角の`Stage::None`セル（閉1つ+開C19/C10）を組み立てる。
    /// `(閉→after, C19→after, C10→after)`。
    fn hz_cells(closed_after: bool, c19_after: bool, c10_after: bool) -> Vec<Cell> {
        use super::super::key_effect_predictor::{cell, Conv, Stage};
        let k = TableKey::HankakuZenkaku;
        vec![
            cell(false, None, Stage::None, k, closed_after, None, Disp::None),
            cell(
                true,
                Some(Conv::C19),
                Stage::None,
                k,
                c19_after,
                Some(Conv::C19),
                Disp::None,
            ),
            cell(
                true,
                Some(Conv::C10),
                Stage::None,
                k,
                c10_after,
                Some(Conv::C10),
                Disp::None,
            ),
        ]
    }

    #[test]
    fn hz_pure_toggle_does_not_omit() {
        assert!(!learned_cells_show_non_toggle(
            &hz_cells(true, false, false),
            TableKey::HankakuZenkaku
        ));
    }

    #[test]
    fn hz_reassigned_to_other_command_omits() {
        let k = TableKey::HankakuZenkaku;
        // IMEOn/ひらがな割当: 閉→開、開→開。
        assert!(learned_cells_show_non_toggle(
            &hz_cells(true, true, true),
            k
        ));
    }

    /// 閉→閉（IMEOff割当）の検出は見送り（閉セル1つのノイズで反転させない）。開セルが開→閉なら外さない。
    #[test]
    fn hz_closed_to_closed_alone_does_not_omit() {
        let k = TableKey::HankakuZenkaku;
        assert!(!learned_cells_show_non_toggle(
            &hz_cells(false, false, false),
            k
        ));
        assert!(!learned_cells_show_non_toggle(
            &hz_cells(false, true, false),
            k
        ));
    }

    #[test]
    fn hz_single_noisy_open_cell_does_not_flip() {
        // 開セル1つだけが開→開（学習ノイズ）でも、残りがトグルなら外さない。
        assert!(!learned_cells_show_non_toggle(
            &hz_cells(true, true, false),
            TableKey::HankakuZenkaku
        ));
    }

    #[test]
    fn hz_no_row_or_missing_cells_does_not_omit() {
        use super::super::key_effect_predictor::{cell, Stage};
        let k = TableKey::HankakuZenkaku;
        assert!(!learned_cells_show_non_toggle(&[], k));
        // 別キーの行だけ（行なし）。
        let other = [cell(
            false,
            None,
            Stage::None,
            TableKey::Henkan,
            false,
            None,
            Disp::None,
        )];
        assert!(!learned_cells_show_non_toggle(&other, k));
        // 閉セルが無い / C10が無い→予測が引けないので外さない。
        let mut no_closed = hz_cells(false, true, true);
        no_closed.remove(0);
        assert!(!learned_cells_show_non_toggle(&no_closed, k));
        let mut no_c10 = hz_cells(false, true, true);
        no_c10.pop();
        assert!(!learned_cells_show_non_toggle(&no_c10, k));
    }

    #[test]
    fn hz_typing_stage_cells_are_ignored() {
        use super::super::key_effect_predictor::{cell, Conv, Stage};
        // MS-IME本体のように、入力中(Typing)の開→開があっても、Noneのセルが純トグルなら外さない。
        let mut cells = hz_cells(true, false, false);
        cells.push(cell(
            true,
            Some(Conv::C19),
            Stage::Typing,
            TableKey::HankakuZenkaku,
            true,
            Some(Conv::C10),
            Disp::Kept,
        ));
        assert!(!learned_cells_show_non_toggle(
            &cells,
            TableKey::HankakuZenkaku
        ));
    }

    /// 同梱表（GJIの2プリセット）は純トグルなので、判定が外さない（誤検出の回帰）。
    #[test]
    fn hz_bundled_gji_tables_are_pure_toggle() {
        for cells in [ATOK, MSIME] {
            assert!(!learned_cells_show_non_toggle(
                cells,
                TableKey::HankakuZenkaku
            ));
        }
    }

    /// `MSIME_NATIVE`（Microsoft IME本体）でも偽だが、理由はGJIと違う: 半角/全角の`Stage::None`に
    /// C10の開セルが無く前提条件を満たさないため偽になる（純トグルだと確認できたわけではない）。
    /// 適用をGJIに限定している理由の一つ（本体の表を判定にかけても外す根拠にならない）。
    #[test]
    fn hz_msime_native_is_false_because_precondition_not_met() {
        assert!(!learned_cells_show_non_toggle(
            MSIME_NATIVE,
            TableKey::HankakuZenkaku
        ));
    }

    fn classify(preset: i64, vk: u16) -> Option<Classification> {
        let keymap = KeyEffectKeymap::from_config(Some(preset), None, &[]).unwrap();
        classify_state_dependent_mode_key(Some(&keymap), vk, None)
    }

    #[test]
    fn adr192_open_axis_verification_table() {
        for vk in [0x16, 0x1A, 0x19, 0xF3, 0xF4] {
            assert_ne!(
                classify(1, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
            assert_ne!(
                classify(2, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
        }
        for vk in [0x1C, 0x1D] {
            assert_eq!(
                classify(1, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
            assert_eq!(classify(2, vk), Some(Classification::StateIndependent));
        }
    }

    #[test]
    fn adr192_composition_axis_verification_table() {
        for preset in [1, 2] {
            for vk in [0x19, 0xF3, 0xF4] {
                assert_eq!(
                    classify(preset, vk),
                    Some(Classification::StateDependent(
                        StateDependentAxis::Composition
                    ))
                );
            }
            for vk in [0x16, 0x1A] {
                assert_eq!(classify(preset, vk), Some(Classification::StateIndependent));
            }
        }
    }

    #[test]
    fn adr192_non_target_keys_are_not_classified() {
        for vk in [0x08, 0x0D, 0x1B, 0x20, 0xF0, 0xF1, 0xF2] {
            assert_eq!(classify(1, vk), None);
        }
    }

    #[test]
    fn adr192_cannot_predict_reasons_are_distinct() {
        assert_eq!(
            classify_state_dependent_mode_key(None, 0x1C, None),
            Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap
            ))
        );
        let overlay = KeyEffectKeymap::from_config(Some(2), None, &[1]).unwrap();
        assert_eq!(
            classify_state_dependent_mode_key(Some(&overlay), 0x1C, None),
            Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap
            ))
        );
        let custom = KeyEffectKeymap::from_config(
            Some(2),
            Some("DirectInput\tHenkan\tIMEOn".to_owned()),
            &[],
        )
        .unwrap();
        assert_eq!(
            classify_state_dependent_mode_key(Some(&custom), 0x1C, None),
            Some(Classification::CannotPredict(
                CannotPredictReason::UserOverride
            ))
        );
        let native = KeyEffectKeymap::for_msime_native(false, None, None);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&native), 0x1C, None),
            Some(Classification::CannotPredict(
                CannotPredictReason::InsufficientData
            ))
        );
    }

    /// ADR192-T5: 学習表が採用されているとき、判定は内蔵表でなく学習表に従う。
    ///
    /// `dependent=false`は変換キーが常にON（セット系＝状態非依存）、`true`は状態によって
    /// トグル/セットが混在する（開閉依存）セル集合。
    fn learned_henkan(dependent: bool) -> Vec<Cell> {
        use super::super::key_effect_predictor::{Conv, Stage};
        let mut cells = vec![
            cell(
                false,
                None,
                Stage::None,
                TableKey::Henkan,
                true,
                Some(Conv::C19),
                Disp::None,
            ),
            cell(
                true,
                Some(Conv::C10),
                Stage::None,
                TableKey::Henkan,
                true,
                Some(Conv::C10),
                Disp::None,
            ),
        ];
        if dependent {
            cells.push(cell(
                true,
                Some(Conv::C19),
                Stage::None,
                TableKey::Henkan,
                false,
                Some(Conv::C19),
                Disp::None,
            ));
        }
        cells
    }

    #[test]
    fn adr192_t5_learned_table_overrides_bundled_classification() {
        let keymap = KeyEffectKeymap::from_config(Some(1), None, &[]).unwrap();
        // 内蔵表(ATOK)では変換キーは開閉依存（既存テスト`adr192_open_axis_verification_table`）。
        assert_eq!(
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, None),
            Some(Classification::StateDependent(StateDependentAxis::Open))
        );
        // 学習表が「常にON」（冪等）と示していれば、警告は出さない側に揃う。
        let idempotent = learned_henkan(false);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, Some(&idempotent)),
            Some(Classification::StateIndependent)
        );
        // 学習表が開閉依存と示していれば、状態依存。
        let dependent = learned_henkan(true);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, Some(&dependent)),
            Some(Classification::StateDependent(StateDependentAxis::Open))
        );
    }

    #[test]
    fn adr192_t5_learned_table_without_the_key_falls_back_to_bundled() {
        use super::super::key_effect_predictor::Stage;
        let keymap = KeyEffectKeymap::from_config(Some(1), None, &[]).unwrap();
        // 学習表に無変換(0x1D)のセルしか無ければ、変換(0x1C)は従来の内蔵表判定のまま。
        let only_muhenkan = [cell(
            false,
            None,
            Stage::None,
            TableKey::Muhenkan,
            true,
            None,
            Disp::None,
        )];
        assert_eq!(
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, Some(&only_muhenkan)),
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, None)
        );
    }

    #[test]
    fn adr192_t5_learned_table_classifies_presets_that_have_no_bundled_table() {
        // Microsoft IME本体は同梱表が無く常に`InsufficientData`だが、学習表があれば判定できる。
        let native = KeyEffectKeymap::for_msime_native(false, None, None);
        let idempotent = learned_henkan(false);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&native), 0x1C, Some(&idempotent)),
            Some(Classification::StateIndependent)
        );
        // keymap自体が不明なら学習表があっても判定しない（何のIMEの表か分からない）。
        assert_eq!(
            classify_state_dependent_mode_key(None, 0x1C, Some(&idempotent)),
            Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap
            ))
        );
    }
}
